### ISSUE TITLE
Enchanced support

### ISSUE THREAD

**Issue by kassane** [kassane/zFFI#2]
## Acceptable Criteria
 
- [ ] Fix comptime support - generic arg_type (requires review)
- [x] Functors members
- [ ] ~~Nested `union` and `struct` support~~ - zig does not support anonymous `union` | `struct`, only anonymous literals (requires review)

---

- https://github.com/eqrion/cbindgen/pull/732

**Comment by kassane** [comment]
Investigate interoperability between generic functions with comptime.

Ref: https://github.com/nekodjin/rusty-ziguanas

**Comment by kassane** [comment]
New issue
- https://github.com/eqrion/cbindgen/pull/732#issuecomment-1324209591

I don't get reviews and my time is short during the weeks (full time job + undergraduate university).
There will be a short time to fix this new problem.

However, I' m not convinced if this modification will be mergeable or not.
It' s not in Mozilla's interest (`cbindgen` maintainers).

Perhaps this conversion may not be very useful for the majority (rust devel), but it doesn't mean that it is unfeasible since they have the interest to abstain from the C language as much as possible to make their applications secure (theoretically).
I also intend, if possible, to make the reverse (zig to rust). But besides the time I will also need to improve my parsing and transpiling skills. I have never worked with compilers or anything like that.

I am curious about some alternatives to `cbindgen`, e.g. [`diplomat`](https://github.com/rust-diplomat/diplomat)(cc: @Manishearth) seems to be simpler. I can't tell if you would be interested in this possible journey. (I need help! :sweat_smile: )

**Comment by Manishearth** [comment]
From Diplomat's POV: We're very happy to support more backends. Note that Diplomat itself does not have the bandwidth to maintain backends we haven't decided to staff, so a Zig backend would be in a similar situation as .NET: We can have the source be in tree and fix it for small changes but we won't actively maintain it and may disable it if we make major changes. In the long run we'd like to not have to do that.


Diplomat _is_ designed to not require backends to be built in-tree, however: you can use the HIR output of the diplomat_core module to build your own that you just maintain based on public Diplomat releases, and we're happy to cut releases whenever ya'll need.

If building a new one I would recommend using the new HIR stuff, the AST infrastructure is deprecated for writing backends. The C2 (i.e. "C but newer") backend is an example of one written on the HIR infrastructure and we plan to work on a C++-HIR one in December, hopefully leading to a lot more improvements there.
